### ISSUE TITLE
Set up Codacy and documentation 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_firefoxbot#1]
* Add Codacy integration through FOSSASIA (not personal repo)
* Move documentation images to `docs/images`

**Comment by hkedia321** [comment]
I would like to work on it :+1:

**Comment by stealthanthrax** [comment]
@hkedia321 , what is the status of this issue?

**Comment by hkedia321** [comment]
I moved the images to docs/images folder. @tstreamDOTh Please add the Codacy integration as I don't have the write access. Let me know if anything else needs to be done.

**Comment by stealthanthrax** [comment]
@mariobehling can I add codacy integration?

**Comment by tstreamDOTh** [comment]
Codacy is already integrated
