### ISSUE TITLE
Table response too long

### ISSUE THREAD

**Issue by hkedia321** [fossasia/susi_firefoxbot#103]
**Actual Behaviour**

The table response is too long, and the user has to scroll through all of it.

**Expected Behaviour**
Lessen the height of the table message.

**Steps to reproduce it**
Ask SUSI queries like "Universities in India"

**Would you like to work on the issue?**
Yes

**Comment by tstreamDOTh** [comment]
@hkedia321 Make it more small will not be readable

**Comment by hkedia321** [comment]
@tstreamDOTh We need to either provide an option to "view more" or we can limit the height, and the user can scroll inside the table. Currently the long table is very annoying for the user. No one wants to see all the results
