### ISSUE TITLE
Hide scroll down button initially when no messages are there

### ISSUE THREAD

**Issue by hkedia321** [fossasia/susi_firefoxbot#107]
**Actual Behaviour**

The "scroll down" button is visible Initially when no messages are there
![godown_firefoxbot](https://user-images.githubusercontent.com/17807257/32641423-d7441ec8-c5f3-11e7-8f4c-121191c39bb9.png)

**Expected Behaviour**

Hide scroll down button Initially when no messages are there

**Steps to reproduce it**

Open the susi firefox extension, and clear any chat history. The scroll down button will be visible.

**Comment by rupav** [comment]
@hkedia321  can I work on it, as GCI is over now?

**Comment by hkedia321** [comment]
@rupav I had already worked on it, and have send a PR(#112)! You can review it and contribute on other issues :)

**Comment by rupav** [comment]
yeah, just saw, no problem, looking the PR, if I understand the code, I will review ✌
