### ISSUE TITLE
Adding Options  to customise UI 

### ISSUE THREAD

**Issue by sk9331657** [fossasia/susi_firefoxbot#134]
**Expected Behaviour**
Adding features like Wallpaper change, different themes similar to Chromebot

**Would you like to work on the issue?**

Yes

**Comment by sk9331657** [comment]
@Ryan10145 I am already working on this.

**Comment by Ryan10145** [comment]
@sk9331657 Oh, sorry, I didn’t realize. I made changes and a pull request because I claimed the task on Google Code In to add a color selector. I didn’t know someone else was working on it.

**Comment by sk9331657** [comment]
Ok then it is fine.

**Comment by tstreamDOTh** [comment]
@sk9331657  This happens a lot. Do you mind taking up some other issue than working on the same

**Comment by sk9331657** [comment]
@tstreamDOTh  Actually I have added myself this task  to gci , so it will be better if you add gci label to it. This task is published . I will take up another issue.
