### ISSUE TITLE
Eye is not proper while logging

### ISSUE THREAD

**Issue by samagragupta** [fossasia/susi_firefoxbot#152]
**Actual Behaviour**

When eye is open the password is not shown vice-versa

**Expected Behaviour**

When eye is open then password should be shown vice-versa

**Screenshots of the issue**

![eye firefox](https://user-images.githubusercontent.com/32234926/48311371-d124ca00-e5c4-11e8-8c42-a426961991e5.PNG)

**Would you like to work on the issue?**

Yes

**Comment by neeraj3029** [comment]
Actually I used the following logic: 
When you want to make the password visible, click on the show button(eye).
When you want to hide the password, click on closed eye button.

**Comment by samagragupta** [comment]
@neeraj3029 Please have a look at Gmail.
![gmail](https://user-images.githubusercontent.com/32234926/48312764-a7c26900-e5d9-11e8-857c-1309ec0d35b0.PNG)

**Comment by neeraj3029** [comment]
Ohh in that case please make the change @samagragupta
