### ISSUE TITLE
Show the correct response from the server

### ISSUE THREAD

**Issue by hkedia321** [fossasia/susi_firefoxbot#17]
**Actual Behaviour**
Shows the incorrect response. It uses the `answers` parameter received from the server

**Expected Behaviour**
Show the correct response. Use the `actions` parameter received from the server

**Screenshots of the issue**
![screenshot from 2017-09-27 16-05-39](https://user-images.githubusercontent.com/17807257/30909254-14f9d546-a39e-11e7-95c5-7de434574247.png)

**Would you like to work on the issue?**

Yes

**Comment by ms10398** [comment]
Isn't this issue a subpart of https://github.com/fossasia/susi_firefoxbot/issues/6

**Comment by ms10398** [comment]
It works fine in my browser

![screenshot from 2017-09-27 16-35-05](https://user-images.githubusercontent.com/26259547/30910367-25e08018-a3a2-11e7-8566-776a706e34c8.png)

You should check once and this issue is already subpart of https://github.com/fossasia/susi_firefoxbot/issues/6

**Comment by hkedia321** [comment]
@ms10398 Please follow the steps shown in the screenshot to recreate the bug. This issue is different from #6. Currently, wrong response is being read from the server's response.

**Comment by ms10398** [comment]
After following the steps to recreate the bug in screenshot still I got the correct response

![screenshot from 2017-09-27 17-31-56](https://user-images.githubusercontent.com/26259547/30912414-0ab1acec-a3aa-11e7-926a-21401bab1787.png)

**Comment by hkedia321** [comment]
@ms10398 It seems you are using a previous version of the extension. Please try using the latest one. This is more in accordance to the susi webchat.

**Comment by ms10398** [comment]
I updated my fork and checked again and still same response
I think we should get a review from someone
@tstreamDOTh Did you try it

**Comment by tstreamDOTh** [comment]
@hkedia321 I am unable to recreate the bug. But yes I too have encountered such spurious results. Inspect more? And I presume this issue will be solved in #6 ? So can we close this?

**Comment by hkedia321** [comment]
We are currently using the wrong parameter from the API response. The correct parameter to be used is `actions`. Please refer the API documentation at https://dev.susi.ai/skills/susi_chat_api.html. This issue can be subpart of #6, so we can close this.
