### ISSUE TITLE
Setup test cases and integrate with travis.

### ISSUE THREAD

**Issue by rishiraj824** [fossasia/susi_firefoxbot#2]
Currently, there are no test cases and the Travis configuration file seems empty. Please write test cases to follow standards.

**Comment by tstreamDOTh** [comment]
(y)

**Comment by ms10398** [comment]
I would like to setup Travis

**Comment by ms10398** [comment]
Travis is working I think @tstreamDOTh

**Comment by tstreamDOTh** [comment]
@ms10398 Yes travis was already integrated. Had to just add the test in configuration.
