### ISSUE TITLE
It does not shows any link or image with message "I found this on the web".

### ISSUE THREAD

**Issue by RMCoder198** [fossasia/susi_firefoxbot#24]
**Actual Behaviour**

whenever susi gives response after searching on the web ,it does not shows any image or link with message with message "I found this on the web".

**Expected Behaviour**
whenever susi gives response after searching on the web ,there should be a link or image with message  "I found this on the web".

**Steps to reproduce it**

      1.Type any celebrity name .
      2.There won't be any image or link in response.

**Screenshots of the issue**
![fire](https://user-images.githubusercontent.com/26675957/31024497-e10497a6-a55c-11e7-93bf-33923eed2702.png)

**Would you like to work on the issue?**

Yes.

**Comment by tstreamDOTh** [comment]
Duplicate #6
