### ISSUE TITLE
Add hyperlink to the search result

### ISSUE THREAD

**Issue by hkedia321** [fossasia/susi_firefoxbot#26]
**Actual Behaviour**

Any link coming from the server is in plain text
![image](https://user-images.githubusercontent.com/17807257/31028160-9cca42f8-a56a-11e7-989b-7c4993105d36.png)

**Expected Behaviour**
Identify any hyperlink in the response and put anchor tag around it.
![image](https://user-images.githubusercontent.com/17807257/31028354-3037422a-a56b-11e7-9237-6349d93c9363.png)

**Steps to reproduce it**

Ask Susi - "Search for fire"

**Would you like to work on the issue?**

No

**Comment by ms10398** [comment]
Yes I would like to work on this

**Comment by nifey** [comment]
I would also like to work on this issue.

**Comment by ms10398** [comment]
Okay sure go ahead with the work I will work on the other issues.
@nifey Good luck!

**Comment by nifey** [comment]
Thanks @ms10398.
