### ISSUE TITLE
Support for table type of response from the server

### ISSUE THREAD

**Issue by hkedia321** [fossasia/susi_firefoxbot#28]
**Actual Behaviour**
When the server sends a response of the type table, Nothing is displayed.

**Expected Behaviour**

The table should be read and displayed.
![image](https://user-images.githubusercontent.com/17807257/31047766-20c00a20-a62e-11e7-87f4-08e242a7925b.png)

**Steps to reproduce it**

Ask susi "Universities in Germany"

**Would you like to work on the issue?**

No.
Anyone working on this can refer to https://dev.susi.ai/skills/susi_chat_api.html.

**Comment by tstreamDOTh** [comment]
Yes I would like to work on it
