### ISSUE TITLE
Create keyboard shortcut for quicker access

### ISSUE THREAD

**Issue by nifey** [fossasia/susi_firefoxbot#31]
**Actual Behaviour**

There is no keyboard shortcut to access the add on.

**Expected Behaviour**

A keyboard shortcut can make it easier and quicker to access SUSI.AI add on. Please suggest if this is necessary. 

**Would you like to work on the issue?**

Yes

**Comment by tstreamDOTh** [comment]
@nifey Yes, we can have this. Go ahead.

**Comment by nifey** [comment]
Ctrl+Shift+S is already used by the debugger. And webextensions does not allow Ctrl+Alt+S. 
So I am thinking of using Alt+Shift+S as the key combination.
Should we go with this?

**Comment by tstreamDOTh** [comment]
@nifey Yes, that will do the job.

**Comment by nifey** [comment]
ok , I'll work on it. @tstreamDOTh
