### ISSUE TITLE
Theme change toggle/icon

### ISSUE THREAD

**Issue by rupav** [fossasia/susi_firefoxbot#35]
**Actual Behaviour**

No icon for theme change.

**Expected Behaviour**
There has to be setting icon in the popup for theme change 

**Steps to reproduce it**
Just like in readme 
**Screenshots of the issue**
I loaded manifest.json
![2017-10-03](https://user-images.githubusercontent.com/20624380/31120274-7978c740-a851-11e7-8c0c-0f7997646b50.png)

**Would you like to work on the issue?**
Yes

**Comment by rupav** [comment]
Hi @tstreamDOTh  I looked your last PR related to change theme, but I am not able to do it

**Comment by tstreamDOTh** [comment]
@rupav The option to change the theme is in extension settings menu. That is where all the settings related to the extension is present.

**Comment by rupav** [comment]
@tstreamDOTh I had to add extension menu. But now clicking on 'Save' is not doing anything i.e not changing theme:
![2017-10-03 2](https://user-images.githubusercontent.com/20624380/31120737-332b69d0-a853-11e7-8a34-d8f04ade6459.png)

**Comment by tstreamDOTh** [comment]
@rupav If you have installed the extension before the cache was added then you need to clear the cache and use it... look into the comments in js file.. uncomment the syn.clear and then run it. Then comment it back. If you still have any issue dm me.
