### ISSUE TITLE
Fix the lag when the popup is opened

### ISSUE THREAD

**Issue by nifey** [fossasia/susi_firefoxbot#37]
**Actual Behaviour**

When we press the addon button, it takes sometime to load previous messages. This lag becomes noticable after using the chat for sometime.

**Expected Behaviour**

I suggest limiting the number of messages restored initially to a finite number (say 10). The older messages can be loaded on demand when the user scrolls up.

Please share your thoughts on this issue.

**Would you like to work on the issue?**

Yes

**Comment by nifey** [comment]
We could also have a button in the settings to clear the chat data.

**Comment by tstreamDOTh** [comment]
How are you planning to do this?

**Comment by nifey** [comment]
I am not quite sure yet. But the rough idea is to modify the restoreMessages function to append a fixed number of older messages to the messages history every time it is called. 

And the use jquery's .scroll() on messages history div. If it detects that the user has scrolled up it will fire the restoreMessages function to load more messages.

**Comment by tstreamDOTh** [comment]
@nifey Please make sure on how you are planning to go about this. Since there are limitations with storage.sync. Just check the feasibility before starting because there are lot more features to be added also, this should not hamper other features.

**Comment by nifey** [comment]
@tstreamdoth I understand. I'll just give it a try. If it doesn't work or changes too many things ,I'll stop working on this.

**Comment by tstreamDOTh** [comment]
@nifey Will be happy if you can find out a solution. Feel free to ask for help.

**Comment by nifey** [comment]
Sure. Thanks @tstreamdoth.
