### ISSUE TITLE
Update .gif in readme

### ISSUE THREAD

**Issue by tstreamDOTh** [fossasia/susi_firefoxbot#44]
**Actual Behaviour**
Outdated .gif in documentation.

**Expected Behaviour**
Make a new .gif of the addon and update it.

**Would you like to work on the issue?**
No

**Comment by marvin08** [comment]
@tstreamDOTh I would like to work on this issue. Can you please help me out and tell me exactly what needs to be done.

**Comment by tstreamDOTh** [comment]
@marvin08 Just look out for the current demo gif in readme. You need to install the addon and record the screen and make a gif out of it.

**Comment by tstreamDOTh** [comment]
@marvin08 are you working on it?

**Comment by marvin08** [comment]
Done. #54

**Comment by marvin08** [comment]
@tstreamDOTh Please review my improved version of PR #57.
Thanks.
