### ISSUE TITLE
Fix typo in chatbot.html

### ISSUE THREAD

**Issue by nifey** [fossasia/susi_firefoxbot#48]
Change the .SVg to .svg in this line
https://github.com/fossasia/susi_firefoxbot/blob/45669ddad9f3dbe6eedb407ddea568857d878f94/src/chatbot.html#L20

### Would you like to work on this?
No

**Comment by rupav** [comment]
I would like to do it. 
Hi @nifey , you can better add a newcomer label :)

**Comment by nifey** [comment]
Yes, this is a newcomer issue. I cannot add because i don't have permission to add labels. 
Anyway glad you are working on this, @rupav .

**Comment by rupav** [comment]
@nifey  looks like a newcomer took up the issue 😀.  I will work on some other :)

**Comment by im-gozmit** [comment]
Hi @nifey , I just corrected the issue and added a pull request .Please have a look on that.

**Comment by nifey** [comment]
@im-gozmit ,Thanks for the changes.
But next time, Please claim an issue and check if someone else is working on it before giving a pull request.
I'm closing this issue now.
