### ISSUE TITLE
Issue with the settings icon.

### ISSUE THREAD

**Issue by AswinChand97** [fossasia/susi_firefoxbot#53]
**Actual Behaviour**

The settings icon is static when hovered upon.

**Expected Behaviour**

The cursor can be changed into a pointer when hovered upon.
The settings icon can also be changed when hovered to create the illusion of a button.

**_Please suggest if this change is necessary..._**

**Screenshots of the issue**

![icon-issue](https://user-images.githubusercontent.com/24192122/31369044-492515c8-ad9f-11e7-8d55-5f69161c8dab.gif)

**Would you like to work on the issue?**

Yes

**Comment by tstreamDOTh** [comment]
@AswinChand97  Add cursor:pointer attribute to settings icon css.

**Comment by AswinChand97** [comment]
Thanks @tstreamDOTh .I will do that. And that change of the settings icon when hovered upon...
is that necessary or can we leave that as it is now?I will attach the gif ... Please suggest whether it is necessary or not..
![icon-fixed](https://user-images.githubusercontent.com/24192122/31397792-8deed9f4-ae04-11e7-9ec0-800d08a8fe55.gif)

**Comment by tstreamDOTh** [comment]
@AswinChand97  Looks good. Can you reverse the effect? Normal state: Only outline and on hover with fill?

**Comment by AswinChand97** [comment]
Thanks a lot @tstreamDOTh .I can do that.
