### ISSUE TITLE
Support for different types of responses from server

### ISSUE THREAD

**Issue by hkedia321** [fossasia/susi_firefoxbot#6]
**Actual Behaviour**
Only text response from the server is shown

**Expected Behaviour**
Support different types of responses like images, links, rss etc. Also select the correct response type from the server.

**Would you like to work on the issue ?**
Yes

**Comment by ms10398** [comment]
@hkedia321 If you need any help in implementing this i am always happy to collaborate.

**Comment by hkedia321** [comment]
Sure @ms10398. Thanks

**Comment by ms10398** [comment]
How is this issue closed if the issue is not yet solved
@tstreamDOTh @hkedia321 

Screenshot of the issue

![screenshot from 2017-09-30 22-05-48](https://user-images.githubusercontent.com/26259547/31047610-aa98ca0a-a62b-11e7-9c60-e9ad5cdd9666.png)

Reviewer should check and close the issues.

**Comment by ms10398** [comment]
Images are not yet displaying.

**Comment by hkedia321** [comment]
@ms10398 This was a relatively large issue to solve. As I mentioned in the PR, we can open different smaller issues so that different people can work on it. Its mentioned in (https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/) that an issue should be broken up if its too large. I have opened an issue #26 for this. Lets open the remaining issues also.
Also as mentioned in the blog, we can make multiple commits in a PR if the feature implemented is quite large. 
I tried to adhere to the best practices as far as possible to my knowledge.

**Comment by ms10398** [comment]
All the commits were related to each other thats why I felt that the commits can be squashed it was a big issue but the issue was not completely resolved thats why there was no need of more than two commits in it according to me.

**Comment by tstreamDOTh** [comment]
@ms10398 Thanks for the advice but I want to bring to your notice that I have squashed and merged. Pls, check the actual commits before making a comment. Also the @hkedia321 pointed out multiple commits can be made if it's a relatively larger issue. This is totally justified. Further discussion is not encouraged. Thanks.

**Comment by hkedia321** [comment]
@ms10398 You are welcome to comment on the PRs. 
@ms10398 @tstreamDOTh Also I have opened #28, #27 and #26. Please open any other issue you think should be there. 
Lets make this extension as perfect as possible. Thank you!

**Comment by tstreamDOTh** [comment]
@ms10398 @hkedia321 Everyone is welcome to discuss but please verify once before posting to have a healthy and meaningful discussion. 👍

**Comment by ms10398** [comment]
I verified @tstreamDOTh according to the practice the one who is a reviewer or maintainer should advice the one who makes a PR to squash the commits.

**Comment by tstreamDOTh** [comment]
@ms10398 I guess I said the same 😊 . And for your kind info, in this case, more than one commit was appropriate. I have answered that and justified clearly.

**Comment by tstreamDOTh** [comment]
@ms10398 @hkedia321 I deleted those comments which were beyond the scope of this issue. We can discuss it on other appropriate channels. 👍
