### ISSUE TITLE
Add communication channel to readme

### ISSUE THREAD

**Issue by geekyd** [fossasia/susi_firefoxbot#65]
**Actual Behaviour**
There is no information about the gitter communication channel.

**Expected Behaviour**
Please add information about gitter channel to readme.md

Please check https://github.com/fossasia/susi_server/blob/development/README.rst#communication

**Comment by rupav** [comment]
@tstreamDOTh @hkedia321 @geekyd you guys can add 'newcomer issue' or 'good first issue' for this :)
