### ISSUE TITLE
Support for different icon sizes

### ISSUE THREAD

**Issue by tstreamDOTh** [fossasia/susi_firefoxbot#7]
**Actual Behaviour**
Currently, only one variant of the icon is being used. (Check the manifest file)

**Expected behaviour**
Add icons of different size to support 

**Would you like to work on the issue?**
No

**Comment by rupav** [comment]
@tstreamDOTh  ,I would like to take this issue. What its about? Can you post a Screenshot here?

**Comment by tstreamDOTh** [comment]
Check the manifest file. Also, refer to documentation https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/icons

**Comment by tstreamDOTh** [comment]
@rupav Working on it?

**Comment by rupav** [comment]
@tstreamDOTh will update you by 12 hrs. from now. Was busy in some other work, So couldnt check this out. I am now doing it.

**Comment by rupav** [comment]
@tstreamDOTh So basically I have to add icons of Susi.ai of different sizes in icons folder, and refer them in "default_icon" in manifest.json file . This is to support icon size in different browser/platform. Am I right?
