### ISSUE TITLE
To add a Susi-styled dropdown-menu

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_firefoxbot#72]
Since many features are being added on a daily basis.We need to add them under a drop-down menu.
Hence organising every thing.
**Expected Behaviour**
To add a dropdown menu combining all the features.

**Steps to reproduce it**
I would  like to create it using  jQuery in it.
**Would you like to work on the issue?**
Yes

**Comment by stealthanthrax** [comment]
@tstreamDOTh,should i start working on it??

**Comment by tstreamDOTh** [comment]
@stealthanthrax This is unnecessary for the time being.

**Comment by stealthanthrax** [comment]
@tstreamDOTh ,let me know if required 👍

**Comment by tstreamDOTh** [comment]
@stealthanthrax Can you explain the purpose of a dropdown here?

**Comment by stealthanthrax** [comment]
@tstreamDOTh ,The main purpose of making the susi firefox bot was that the user doesn't have to leave his/her work to use SUSI .But having to open a seperate page for minor tweaks really destroys the purpose.

**Comment by tstreamDOTh** [comment]
The addons settings page exclusively dedicated for the extension settings. It is the appropriate place to keep all settings options and is a good practice. This is not appropriate for the project. Also, we are having extensive settings options coming up so keeping everything inside the popup will look clustered,
