### ISSUE TITLE
Time formatting for retrieved messages

### ISSUE THREAD

**Issue by tstreamDOTh** [fossasia/susi_firefoxbot#79]
**Actual Behaviour**
Currently, the time format for retrieved messages is HH:MM:SS

**Expected Behaviour**
Time format must be HH:MM

**Would you like to work on the issue?**
Yes

**Comment by rupav** [comment]
@tstreamDOTh, why do you want this format. I think having seconds also is apt.

**Comment by tstreamDOTh** [comment]
@rupav The time format is in hh:mm in susi web chat
