### ISSUE TITLE
Nothing showing from the web.

### ISSUE THREAD

**Issue by rupav** [fossasia/susi_firefoxbot#8]
![2017-09-26 2](https://user-images.githubusercontent.com/20624380/30866010-beec9baa-a2f5-11e7-8816-4e220bb023e0.png)
![2017-09-26 1](https://user-images.githubusercontent.com/20624380/30866034-c6dfdbce-a2f5-11e7-9437-d033d13d8bfe.png)

**Comment by tstreamDOTh** [comment]
@rupav The issue has been opened at https://github.com/fossasia/susi_firefoxbot/issues/6

**Comment by rupav** [comment]
oh ok @tstreamDOTh .
