### ISSUE TITLE
Theme selection dropdown is buggy

### ISSUE THREAD

**Issue by aashutoshrathi** [fossasia/susi_firefoxbot#98]
**Actual Behaviour**

Please state here what is currently happening.
![image](https://user-images.githubusercontent.com/21199234/32074527-49e9d938-bab7-11e7-8585-cfc9746ca4f5.png)

**Expected Behavior**

The drop down should be attached with its parent and can have a better UI.

**Steps to reproduce it**

Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

**Screenshots of the issue**

attached above

**Would you like to work on the issue?**

Yes

**Comment by tstreamDOTh** [comment]
#96 Duplicate
